"""add models/info_card and modified models/post

Revision ID: 237169e8c5c8
Revises: 6242182cf403
Create Date: 2026-03-04 14:36:39.213619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237169e8c5c8'
down_revision = '6242182cf403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info_card')
    # ### end Alembic commands ###
