"""add image  to commune, for cards in public

Revision ID: 3afeb4154747
Revises: 8d2cb15fcaeb
Create Date: 2026-03-12 01:40:05.996065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afeb4154747'
down_revision = '8d2cb15fcaeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communes', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
