"""add table documents, with categorys for cards lettreres, deliberations, arretes

Revision ID: 654ead05b1bf
Revises: 94a1f1d4844a
Create Date: 2026-03-09 13:51:13.644801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654ead05b1bf'
down_revision = '94a1f1d4844a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
